# @host=http://localhost:8080
@host=https://rebalancer.connextapi.com

GET {{host}}/ping

##################

POST {{host}}/matic/deposit/approval
Content-Type: application/json

{
  "amount": "100",
  "assetId": "0x0F5D2fB29fb7d3CFeE444a200298f468908cC942",
  "signer": "0xe6887c0cc3c37cb2ee34bc58ab258f36825ca910",
  "fromProvider": "https://mainnet.infura.io/v3/",
  "fromChainId": 1,
  "toProvider": "https://rpc-mainnet.matic.network",
  "toChainId": 137
}

##################

POST {{host}}/matic/deposit/execute
Content-Type: application/json

{
  "amount": "76478066937229740000000",
  "assetId": "0x0F5D2fB29fb7d3CFeE444a200298f468908cC942",
  "signer": "0xe6887c0cc3c37cb2ee34bc58ab258f36825ca910",
  "fromProvider": "https://mainnet.infura.io/v3/",
  "fromChainId": 1,
  "toProvider": "https://rpc-mainnet.matic.network",
  "toChainId": 137
}

##################

POST {{host}}/matic/deposit/status
Content-Type: application/json

{
  "amount": "100",
  "assetId": "0x0F5D2fB29fb7d3CFeE444a200298f468908cC942",
  "signer": "0xe6887c0cc3c37cb2ee34bc58ab258f36825ca910",
  "fromProvider": "https://mainnet.infura.io/v3/",
  "fromChainId": 1,
  "toProvider": "https://rpc-mainnet.matic.network",
  "toChainId": 137,
  "txHash": "0xa5786b2dc3a342eb3b1935ef38c34e8f6137101b85bcf63ab540b0108feaeaf5"
}