@host=http://localhost:8080
# @host=https://rebalancer.connextapi.com

GET {{host}}/ping

##################

POST {{host}}/matic/deposit/approval
Content-Type: application/json

{
  "amount": "50000000000000000000",
  "assetId": "0x655F2166b0709cd575202630952D71E2bB0d61Af",
  "fromProvider": "https://eth-goerli.alchemyapi.io/v2/SU-VoQIQnzxwTrccH4tfjrQRTCrNiX6w",
  "fromChainId": 5,
  "toProvider": "https://rpc-mumbai.matic.today",
  "toChainId": 80001,
  "signer": "0x9CD130fE9aC1EF5173eEBE0C163C7a19f3E4ed2B"
}

##################

POST {{host}}/matic/deposit/execute
Content-Type: application/json

{
  "amount": "10000000000000000000",
  "assetId": "0x655f2166b0709cd575202630952d71e2bb0d61af",
  "signer": "0x18EdaEc676341D63d7087D0d999cF1f1a56d565A",
  "fromProvider": "https://goerli.infura.io/v3/",
  "fromChainId": 5,
  "toProvider": "https://rpc-mumbai.matic.today",
  "toChainId": 80001
}

##################

POST {{host}}/matic/deposit/status
Content-Type: application/json

{
  "fromProvider": "https://goerli.infura.io/v3/",
  "fromChainId": 5,
  "toProvider": "https://rpc-mumbai.matic.today",
  "toChainId": 80001,
  "txHash": "0x6b6140290037607c8c8540e185d8b95295bbd27ff8c18de77ab5d565106bd993",
  "signer": "0x18EdaEc676341D63d7087D0d999cF1f1a56d565A",
  "blockNumber": 4382195
}

##################
POST {{host}}/matic/withdraw/approval
Content-Type: application/json

{
  "amount": "10000000000000000000",
  "assetId": "0xfe4F5145f6e09952a5ba9e956ED0C25e3Fa4c7F1",
  "signer": "0x18EdaEc676341D63d7087D0d999cF1f1a56d565A",
  "toProvider": "https://goerli.infura.io/v3/",
  "toChainId": 5,
  "fromProvider": "https://rpc-mumbai.matic.today",
  "fromChainId": 80001
}

##################
POST {{host}}/matic/withdraw/execute
Content-Type: application/json

{
  "amount": "10000000000000000000",
  "assetId": "0xfe4F5145f6e09952a5ba9e956ED0C25e3Fa4c7F1",
  "signer": "0x18EdaEc676341D63d7087D0d999cF1f1a56d565A",
  "toProvider": "https://goerli.infura.io/v3/",
  "toChainId": 5,
  "fromProvider": "https://rpc-mumbai.matic.today",
  "fromChainId": 80001
}


##################
POST {{host}}/matic/withdraw/status
Content-Type: application/json

{
  "toProvider": "https://goerli.infura.io/v3/",
  "toChainId": 5,
  "fromProvider": "https://rpc-mumbai.matic.today",
  "fromChainId": 80001,
  "txHash": "0x19cb5364985b07b03b4d600c5700ecbe92cb0949502902d52c05b1f72d6b5559",
  "signer": "0x18EdaEc676341D63d7087D0d999cF1f1a56d565A",
}
